### ISSUE TITLE
No Global Menu

### ISSUE THREAD

**Issue by AbhishekZambaremPHATEK** [cutefishos/statusbar#2]
it is based on KDE so it might be easy to add global menu

**Comment by Macintosh98** [comment]
mac os look without global menu is not good

**Comment by HansJK** [comment]
Indeed, it's such a big part of the macOS look and feel.

**Comment by reionwong** [comment]
WIP :)

![Screenshot from 2021-06-06 14-07-26](https://user-images.githubusercontent.com/9636382/120914469-fde3e400-c6d0-11eb-90cc-b5efe41b502d.png)

**Comment by AbhishekZambaremPHATEK** [comment]
great work, when it will be available for us to try? and when this will be available it will be better look than elementaryOS

**Comment by reionwong** [comment]
> great work, when it will be available for us to try? and when this will be available it will be better look than elementaryOS

Probably in the next version 0.3

**Comment by AbhishekZambaremPHATEK** [comment]
I am exited to see this distro grow
