### ISSUE TITLE
Unknown CMake command "qt_add_dbus_interface".

### ISSUE THREAD

**Issue by imChipo** [cutefishos/statusbar#3]
arm:~/dvp/cutefish/statusbar/build$ cmake ..

CMake Error at CMakeLists.txt:82 (qt_add_dbus_interface):
  Unknown CMake command "qt_add_dbus_interface".
-- Configuring incomplete, errors occurred!

**Comment by reionwong** [comment]
Can you send the QT version and CMake version of your environment?

**Comment by imChipo** [comment]
> Can you send the QT version and CMake version of your environment?

arm:~$ qmake --version
QMake version 3.1
Using Qt version 5.14.2 in /usr/lib/aarch64-linux-gnu

arm:~$ cmake --version
cmake version 3.16.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by reionwong** [comment]
Thank you for your feedback, this module `qt_add_dbus_interface` was added on Qt5.15, I plan to make it compile before 5.15 :)
